### PR TITLE
Wizarding

### PR DESCRIPTION
**Pull request by linuxwolf**
simpistic "back" button.  Right now this only enables when "continue" enables, which is less than ideal.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@linuxwolf, the UX folks want to initially test without the back button. Will integrate after they finish their testing.

**Comment by marcoscaceres** [comment]
I'll merge in the webpack and package suggestions... thanks for those!

**Comment by marcoscaceres** [comment]
Going to implement back differently. Hopefully will have something to show tomorrow

**Comment by linuxwolf** [comment]
👍

**Pull request closed without merging**
